# Generated by Django 3.2.2 on 2021-05-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('narx', models.FloatField()),
                ('tarif', models.TextField(null=True)),
                ('soni', models.IntegerField(default=10)),
            ],
        ),
    ]
