# Generated by Django 3.2.2 on 2021-05-23 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='toifasi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.toifa'),
        ),
    ]
