# Generated by Django 3.2.2 on 2021-05-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210523_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='rasm',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='nomi',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='toifa',
            name='nomi',
            field=models.CharField(max_length=50, verbose_name='Toifa nomi'),
        ),
    ]
